In [2]:
# All Libraries required for this lab are listed below. 


!pip install numpy==2.0.2
!pip install pandas==2.2.2
!pip install tensorflow_cpu==2.18.0

Requirement already satisfied: numpy==2.0.2 in c:\docs\ibm\ibm_env\lib\site-packages (2.0.2)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas==2.2.2 in c:\docs\ibm\ibm_env\lib\site-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\docs\ibm\ibm_env\lib\site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\docs\ibm\ibm_env\lib\site-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in c:\docs\ibm\ibm_env\lib\site-packages (from pandas==2.2.2) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\docs\ibm\ibm_env\lib\site-packages (from pandas==2.2.2) (2026.3)
Requirement already satisfied: six>=1.5 in c:\docs\ibm\ibm_env\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: tensorflow_cpu==2.18.0 in c:\docs\ibm\ibm_env\lib\site-packages (2.18.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow_cpu==2.18.0) (2.18.0)
Requirement already satisfied: packaging in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (26.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2.34.2)
Requirement already satisfied: h5py>=3.11.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2.2.2)
Requirement already satisfied: setuptools in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (83.0.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.31.0)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (25.12.19)
Requirement already satisfied: keras>=3.5.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.12.3)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.7.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (5.29.6)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.4.1)
Requirement already satisfied: termcolor>=1.1.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.3.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.2.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2.18.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (4.16.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2.0.2)
Requirement already satisfied: absl-py>=1.0.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (1.6.3)
Requirement already satisfied: six>=1.12.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (1.82.1)
Requirement already satisfied: libclang>=13.0.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (18.1.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\docs\ibm\ibm_env\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.47.0)
Requirement already satisfied: optree in c:\docs\ibm\ibm_env\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.19.1)
Requirement already satisfied: rich in c:\docs\ibm\ibm_env\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (15.0.0)
Requirement already satisfied: namex in c:\docs\ibm\ibm_env\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\docs\ibm\ibm_env\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.4.9)
Requirement already satisfied: certifi>=2023.5.7 in c:\docs\ibm\ibm_env\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2026.7.22)
Requirement already satisfied: idna<4,>=2.5 in c:\docs\ibm\ibm_env\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\docs\ibm\ibm_env\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2.7.0)
Requirement already satisfied: werkzeug>=1.0.1 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.1.8)
Requirement already satisfied: markdown>=2.6.8 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\docs\ibm\ibm_env\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.7.2)
Requirement already satisfied: markupsafe>=2.1.1 in c:\docs\ibm\ibm_env\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\docs\ibm\ibm_env\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\docs\ibm\ibm_env\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\docs\ibm\ibm_env\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow_cpu==2.18.0) (0.1.2)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [4]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [5]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [6]:
concrete_data.shape

(1030, 9)

In [7]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [8]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [9]:
concrete_data_columns = concrete_data.columns

In [10]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [11]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [12]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [13]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [14]:
n_cols = predictors_norm.shape[1] # number of predictors

<a id="item1"></a>

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

In [16]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [17]:
# build the model
model = regression_model()

In [18]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 46ms/step - loss: 1640.6843 - val_loss: 1141.0490
Epoch 2/100
23/23 - 0s - 4ms/step - loss: 1515.0397 - val_loss: 1018.0966
Epoch 3/100
23/23 - 0s - 5ms/step - loss: 1309.1208 - val_loss: 833.7795
Epoch 4/100
23/23 - 0s - 5ms/step - loss: 996.9608 - val_loss: 592.8062
Epoch 5/100
23/23 - 0s - 5ms/step - loss: 634.3653 - val_loss: 364.1593
Epoch 6/100
23/23 - 0s - 5ms/step - loss: 351.0750 - val_loss: 236.1156
Epoch 7/100
23/23 - 0s - 4ms/step - loss: 242.1570 - val_loss: 201.0705
Epoch 8/100
23/23 - 0s - 5ms/step - loss: 221.4253 - val_loss: 186.4939
Epoch 9/100
23/23 - 0s - 5ms/step - loss: 210.4347 - val_loss: 179.0772
Epoch 10/100
23/23 - 0s - 5ms/step - loss: 201.1961 - val_loss: 173.2738
Epoch 11/100
23/23 - 0s - 5ms/step - loss: 194.9395 - val_loss: 172.4315
Epoch 12/100
23/23 - 0s - 6ms/step - loss: 188.8199 - val_loss: 167.4146
Epoch 13/100
23/23 - 0s - 5ms/step - loss: 183.4974 - val_loss: 164.7182
Epoch 14/100
23/23 - 0s - 5ms/step - loss: 179.1708 - val_loss: 160.2322
Epoch 15/100
23/23 - 0s - 4ms/step - loss: 175.1995 - val_loss: 156.3537
Epoch 16/100
23/23 - 0s - 4ms/step - loss: 171.9721 - val_loss: 153.0580
Epoch 17/100
23/23 - 0s - 5ms/step - loss: 169.2398 - val_loss: 153.5307
Epoch 18/100
23/23 - 0s - 5ms/step - loss: 166.3169 - val_loss: 149.5112
Epoch 19/100
23/23 - 0s - 5ms/step - loss: 163.7544 - val_loss: 149.0648
Epoch 20/100
23/23 - 0s - 6ms/step - loss: 161.1749 - val_loss: 149.0255
Epoch 21/100
23/23 - 0s - 6ms/step - loss: 159.0408 - val_loss: 145.9334
Epoch 22/100
23/23 - 0s - 5ms/step - loss: 157.1178 - val_loss: 144.6489
Epoch 23/100
23/23 - 0s - 5ms/step - loss: 155.1479 - val_loss: 145.7565
Epoch 24/100
23/23 - 0s - 4ms/step - loss: 153.7738 - val_loss: 145.4683
Epoch 25/100
23/23 - 0s - 6ms/step - loss: 151.3332 - val_loss: 141.7676
Epoch 26/100
23/23 - 0s - 6ms/step - loss: 150.0732 - val_loss: 142.3369
Epoch 27/100
23/23 - 0s - 5ms/step - loss: 148.0181 - val_loss: 140.8850
Epoch 28/100
23/23 - 0s - 5ms/step - loss: 146.3593 - val_loss: 141.2006
Epoch 29/100
23/23 - 0s - 4ms/step - loss: 144.7664 - val_loss: 141.5077
Epoch 30/100
23/23 - 0s - 4ms/step - loss: 143.1715 - val_loss: 140.0535
Epoch 31/100
23/23 - 0s - 5ms/step - loss: 142.0870 - val_loss: 139.4132
Epoch 32/100
23/23 - 0s - 5ms/step - loss: 140.3159 - val_loss: 138.8747
Epoch 33/100
23/23 - 0s - 4ms/step - loss: 138.8822 - val_loss: 139.7858
Epoch 34/100
23/23 - 0s - 4ms/step - loss: 137.5530 - val_loss: 139.6345
Epoch 35/100
23/23 - 0s - 4ms/step - loss: 136.6850 - val_loss: 137.8661
Epoch 36/100
23/23 - 0s - 4ms/step - loss: 134.9032 - val_loss: 137.8459
Epoch 37/100
23/23 - 0s - 4ms/step - loss: 133.4821 - val_loss: 138.2005
Epoch 38/100
23/23 - 0s - 4ms/step - loss: 131.5961 - val_loss: 139.6507
Epoch 39/100
23/23 - 0s - 4ms/step - loss: 130.5793 - val_loss: 139.4026
Epoch 40/100
23/23 - 0s - 5ms/step - loss: 128.9333 - val_loss: 137.1778
Epoch 41/100
23/23 - 0s - 4ms/step - loss: 127.6717 - val_loss: 138.1201
Epoch 42/100
23/23 - 0s - 5ms/step - loss: 125.7101 - val_loss: 137.1955
Epoch 43/100
23/23 - 0s - 5ms/step - loss: 124.0834 - val_loss: 138.6442
Epoch 44/100
23/23 - 0s - 5ms/step - loss: 121.8446 - val_loss: 136.9404
Epoch 45/100
23/23 - 0s - 5ms/step - loss: 120.4847 - val_loss: 137.3767
Epoch 46/100
23/23 - 0s - 5ms/step - loss: 118.4022 - val_loss: 135.8979
Epoch 47/100
23/23 - 0s - 4ms/step - loss: 115.7299 - val_loss: 135.7508
Epoch 48/100
23/23 - 0s - 4ms/step - loss: 113.1054 - val_loss: 133.9421
Epoch 49/100
23/23 - 0s - 5ms/step - loss: 110.7036 - val_loss: 133.3527
Epoch 50/100
23/23 - 0s - 5ms/step - loss: 108.5624 - val_loss: 134.1743
Epoch 51/100
23/23 - 0s - 5ms/step - loss: 105.6674 - val_loss: 130.2870
Epoch 52/100
23/23 - 0s - 4ms/step - loss: 103.1374 - val_loss: 128.2990
Epoch 53/100
23/23 - 0s - 4ms/step - loss: 99.7034 - val_loss: 127.5031
Epoch 54/100
23/23 - 0s - 4ms/step - loss: 96.3837 - val_loss: 125.6504
Epoch 55/100
23/23 - 0s - 4ms/step - loss: 92.9897 - val_loss: 125.7408
Epoch 56/100
23/23 - 0s - 4ms/step - loss: 89.0677 - val_loss: 124.3010
Epoch 57/100
23/23 - 0s - 8ms/step - loss: 85.4892 - val_loss: 123.7359
Epoch 58/100
23/23 - 0s - 5ms/step - loss: 82.0541 - val_loss: 116.6382
Epoch 59/100
23/23 - 0s - 5ms/step - loss: 78.2152 - val_loss: 120.8034
Epoch 60/100
23/23 - 0s - 5ms/step - loss: 74.7197 - val_loss: 122.1718
Epoch 61/100
23/23 - 0s - 5ms/step - loss: 71.1851 - val_loss: 120.1695
Epoch 62/100
23/23 - 0s - 5ms/step - loss: 67.9309 - val_loss: 117.3585
Epoch 63/100
23/23 - 0s - 5ms/step - loss: 65.1303 - val_loss: 111.9885
Epoch 64/100
23/23 - 0s - 5ms/step - loss: 62.4827 - val_loss: 117.0199
Epoch 65/100
23/23 - 0s - 5ms/step - loss: 59.6529 - val_loss: 118.8578
Epoch 66/100
23/23 - 0s - 5ms/step - loss: 57.3362 - val_loss: 119.1431
Epoch 67/100
23/23 - 0s - 5ms/step - loss: 55.8602 - val_loss: 115.0318
Epoch 68/100
23/23 - 0s - 6ms/step - loss: 54.3716 - val_loss: 119.6184
Epoch 69/100
23/23 - 0s - 5ms/step - loss: 52.3140 - val_loss: 127.3746
Epoch 70/100
23/23 - 0s - 5ms/step - loss: 50.9840 - val_loss: 126.0159
Epoch 71/100
23/23 - 0s - 5ms/step - loss: 50.0171 - val_loss: 117.9444
Epoch 72/100
23/23 - 0s - 4ms/step - loss: 49.6406 - val_loss: 122.6538
Epoch 73/100
23/23 - 0s - 4ms/step - loss: 47.9854 - val_loss: 129.8464
Epoch 74/100
23/23 - 0s - 5ms/step - loss: 47.1916 - val_loss: 135.7178
Epoch 75/100
23/23 - 0s - 5ms/step - loss: 46.0917 - val_loss: 128.8030
Epoch 76/100
23/23 - 0s - 5ms/step - loss: 44.8012 - val_loss: 131.6261
Epoch 77/100
23/23 - 0s - 4ms/step - loss: 44.3987 - val_loss: 134.6118
Epoch 78/100
23/23 - 0s - 5ms/step - loss: 43.4936 - val_loss: 133.3949
Epoch 79/100
23/23 - 0s - 5ms/step - loss: 42.9987 - val_loss: 142.9858
Epoch 80/100
23/23 - 0s - 5ms/step - loss: 42.2971 - val_loss: 141.5123
Epoch 81/100
23/23 - 0s - 5ms/step - loss: 42.1353 - val_loss: 125.5331
Epoch 82/100
23/23 - 0s - 5ms/step - loss: 41.5039 - val_loss: 136.0588
Epoch 83/100
23/23 - 0s - 4ms/step - loss: 40.4720 - val_loss: 134.6152
Epoch 84/100
23/23 - 0s - 8ms/step - loss: 40.4259 - val_loss: 153.6863
Epoch 85/100
23/23 - 0s - 5ms/step - loss: 39.5224 - val_loss: 135.5909
Epoch 86/100
23/23 - 0s - 5ms/step - loss: 39.7133 - val_loss: 141.0863
Epoch 87/100
23/23 - 0s - 5ms/step - loss: 38.9415 - val_loss: 157.2032
Epoch 88/100
23/23 - 0s - 4ms/step - loss: 39.0890 - val_loss: 137.3103
Epoch 89/100
23/23 - 0s - 4ms/step - loss: 37.7449 - val_loss: 140.3326
Epoch 90/100
23/23 - 0s - 4ms/step - loss: 37.3965 - val_loss: 149.2306
Epoch 91/100
23/23 - 0s - 5ms/step - loss: 36.9824 - val_loss: 148.6084
Epoch 92/100
23/23 - 0s - 4ms/step - loss: 36.6785 - val_loss: 136.9705
Epoch 93/100
23/23 - 0s - 4ms/step - loss: 36.1006 - val_loss: 143.3089
Epoch 94/100
23/23 - 0s - 4ms/step - loss: 35.8156 - val_loss: 143.4565
Epoch 95/100
23/23 - 0s - 4ms/step - loss: 35.6218 - val_loss: 138.6978
Epoch 96/100
23/23 - 0s - 5ms/step - loss: 35.2686 - val_loss: 149.1173
Epoch 97/100
23/23 - 0s - 5ms/step - loss: 35.1903 - val_loss: 148.8796
Epoch 98/100
23/23 - 0s - 5ms/step - loss: 34.5434 - val_loss: 141.2860
Epoch 99/100
23/23 - 0s - 5ms/step - loss: 33.9749 - val_loss: 149.2264
Epoch 100/100
23/23 - 0s - 5ms/step - loss: 33.8322 - val_loss: 140.4573

Now using the same dateset,try to recreate regression model featuring five hidden layers, each with 50 nodes and ReLU activation functions, a single output layer, optimized using the Adam optimizer.

In [19]:
def regression_model():
    input_colm = predictors_norm.shape[1] # Number of input features
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  # Set the number of input features 
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu')) 
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(1))  # Output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

 Train and evaluate the model simultaneously using the fit() method by reserving 10% of the data for validation and training the model for 100 epochs

In [20]:
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 1s - 46ms/step - loss: 1422.3140 - val_loss: 721.9134
Epoch 2/100
29/29 - 0s - 4ms/step - loss: 455.5748 - val_loss: 211.6069
Epoch 3/100
29/29 - 0s - 4ms/step - loss: 237.4147 - val_loss: 201.4104
Epoch 4/100
29/29 - 0s - 6ms/step - loss: 206.4217 - val_loss: 190.2367
Epoch 5/100
29/29 - 0s - 4ms/step - loss: 185.5883 - val_loss: 179.7734
Epoch 6/100
29/29 - 0s - 4ms/step - loss: 169.8461 - val_loss: 167.3006
Epoch 7/100
29/29 - 0s - 4ms/step - loss: 154.3659 - val_loss: 155.5591
Epoch 8/100
29/29 - 0s - 4ms/step - loss: 143.7127 - val_loss: 140.9024
Epoch 9/100
29/29 - 0s - 4ms/step - loss: 128.2592 - val_loss: 123.7703
Epoch 10/100
29/29 - 0s - 4ms/step - loss: 110.5936 - val_loss: 115.6054
Epoch 11/100
29/29 - 0s - 4ms/step - loss: 99.5267 - val_loss: 114.7397
Epoch 12/100
29/29 - 0s - 4ms/step - loss: 89.5885 - val_loss: 93.5814
Epoch 13/100
29/29 - 0s - 4ms/step - loss: 78.2824 - val_loss: 96.8602
Epoch 14/100
29/29 - 0s - 4ms/step - loss: 72.4113 - val_loss: 78.3743
Epoch 15/100
29/29 - 0s - 4ms/step - loss: 66.0856 - val_loss: 63.0396
Epoch 16/100
29/29 - 0s - 4ms/step - loss: 62.3155 - val_loss: 64.7318
Epoch 17/100
29/29 - 0s - 4ms/step - loss: 55.4242 - val_loss: 65.3722
Epoch 18/100
29/29 - 0s - 5ms/step - loss: 52.1279 - val_loss: 60.1319
Epoch 19/100
29/29 - 0s - 4ms/step - loss: 48.6606 - val_loss: 53.7175
Epoch 20/100
29/29 - 0s - 4ms/step - loss: 46.0729 - val_loss: 54.5354
Epoch 21/100
29/29 - 0s - 4ms/step - loss: 43.6008 - val_loss: 60.8490
Epoch 22/100
29/29 - 0s - 4ms/step - loss: 41.7032 - val_loss: 43.3913
Epoch 23/100
29/29 - 0s - 4ms/step - loss: 39.9348 - val_loss: 53.8625
Epoch 24/100
29/29 - 0s - 4ms/step - loss: 38.8369 - val_loss: 45.8564
Epoch 25/100
29/29 - 0s - 4ms/step - loss: 35.9132 - val_loss: 41.0663
Epoch 26/100
29/29 - 0s - 4ms/step - loss: 34.6785 - val_loss: 46.8082
Epoch 27/100
29/29 - 0s - 4ms/step - loss: 34.2424 - val_loss: 44.6673
Epoch 28/100
29/29 - 0s - 4ms/step - loss: 33.5078 - val_loss: 47.5097
Epoch 29/100
29/29 - 0s - 4ms/step - loss: 32.8608 - val_loss: 41.0925
Epoch 30/100
29/29 - 0s - 4ms/step - loss: 30.1982 - val_loss: 38.2985
Epoch 31/100
29/29 - 0s - 4ms/step - loss: 29.7245 - val_loss: 28.3196
Epoch 32/100
29/29 - 0s - 4ms/step - loss: 29.1021 - val_loss: 28.7102
Epoch 33/100
29/29 - 0s - 4ms/step - loss: 27.3925 - val_loss: 27.6902
Epoch 34/100
29/29 - 0s - 5ms/step - loss: 28.3840 - val_loss: 35.7633
Epoch 35/100
29/29 - 0s - 4ms/step - loss: 27.9947 - val_loss: 25.9943
Epoch 36/100
29/29 - 0s - 4ms/step - loss: 27.7888 - val_loss: 25.2804
Epoch 37/100
29/29 - 0s - 6ms/step - loss: 25.3063 - val_loss: 35.8184
Epoch 38/100
29/29 - 0s - 4ms/step - loss: 24.7115 - val_loss: 26.5469
Epoch 39/100
29/29 - 0s - 4ms/step - loss: 25.4153 - val_loss: 27.6194
Epoch 40/100
29/29 - 0s - 4ms/step - loss: 24.3096 - val_loss: 30.6185
Epoch 41/100
29/29 - 0s - 4ms/step - loss: 24.1354 - val_loss: 27.8308
Epoch 42/100
29/29 - 0s - 4ms/step - loss: 24.0496 - val_loss: 27.3664
Epoch 43/100
29/29 - 0s - 4ms/step - loss: 22.5279 - val_loss: 23.8882
Epoch 44/100
29/29 - 0s - 4ms/step - loss: 21.7861 - val_loss: 27.7500
Epoch 45/100
29/29 - 0s - 4ms/step - loss: 21.7640 - val_loss: 30.1489
Epoch 46/100
29/29 - 0s - 4ms/step - loss: 22.9584 - val_loss: 21.3732
Epoch 47/100
29/29 - 0s - 4ms/step - loss: 21.0834 - val_loss: 24.4798
Epoch 48/100
29/29 - 0s - 5ms/step - loss: 20.6027 - val_loss: 23.8177
Epoch 49/100
29/29 - 0s - 5ms/step - loss: 21.7732 - val_loss: 21.3871
Epoch 50/100
29/29 - 0s - 4ms/step - loss: 19.9769 - val_loss: 31.9963
Epoch 51/100
29/29 - 0s - 4ms/step - loss: 21.4286 - val_loss: 28.2125
Epoch 52/100
29/29 - 0s - 5ms/step - loss: 19.7944 - val_loss: 19.6409
Epoch 53/100
29/29 - 0s - 5ms/step - loss: 19.3802 - val_loss: 25.9607
Epoch 54/100
29/29 - 0s - 5ms/step - loss: 18.7101 - val_loss: 23.9086
Epoch 55/100
29/29 - 0s - 5ms/step - loss: 18.9568 - val_loss: 19.4329
Epoch 56/100
29/29 - 0s - 4ms/step - loss: 18.5767 - val_loss: 20.3820
Epoch 57/100
29/29 - 0s - 4ms/step - loss: 17.6222 - val_loss: 25.9081
Epoch 58/100
29/29 - 0s - 4ms/step - loss: 17.2593 - val_loss: 19.1017
Epoch 59/100
29/29 - 0s - 4ms/step - loss: 17.4110 - val_loss: 23.7974
Epoch 60/100
29/29 - 0s - 5ms/step - loss: 16.9304 - val_loss: 21.0168
Epoch 61/100
29/29 - 0s - 5ms/step - loss: 16.4747 - val_loss: 19.2961
Epoch 62/100
29/29 - 0s - 5ms/step - loss: 16.7164 - val_loss: 26.7436
Epoch 63/100
29/29 - 0s - 4ms/step - loss: 15.6565 - val_loss: 23.7762
Epoch 64/100
29/29 - 0s - 4ms/step - loss: 17.0779 - val_loss: 17.9185
Epoch 65/100
29/29 - 0s - 4ms/step - loss: 17.7720 - val_loss: 28.4834
Epoch 66/100
29/29 - 0s - 4ms/step - loss: 15.9231 - val_loss: 19.7097
Epoch 67/100
29/29 - 0s - 4ms/step - loss: 15.4002 - val_loss: 20.3734
Epoch 68/100
29/29 - 0s - 5ms/step - loss: 14.4528 - val_loss: 22.9877
Epoch 69/100
29/29 - 0s - 4ms/step - loss: 15.8448 - val_loss: 19.5690
Epoch 70/100
29/29 - 0s - 4ms/step - loss: 15.2386 - val_loss: 18.3739
Epoch 71/100
29/29 - 0s - 5ms/step - loss: 16.0096 - val_loss: 23.5236
Epoch 72/100
29/29 - 0s - 5ms/step - loss: 13.9579 - val_loss: 19.0937
Epoch 73/100
29/29 - 0s - 4ms/step - loss: 14.1589 - val_loss: 21.0184
Epoch 74/100
29/29 - 0s - 4ms/step - loss: 13.8405 - val_loss: 21.8432
Epoch 75/100
29/29 - 0s - 4ms/step - loss: 13.6868 - val_loss: 20.2506
Epoch 76/100
29/29 - 0s - 4ms/step - loss: 14.5828 - val_loss: 21.6407
Epoch 77/100
29/29 - 0s - 4ms/step - loss: 15.0864 - val_loss: 22.9364
Epoch 78/100
29/29 - 0s - 5ms/step - loss: 15.3771 - val_loss: 19.7090
Epoch 79/100
29/29 - 0s - 4ms/step - loss: 13.9303 - val_loss: 18.1398
Epoch 80/100
29/29 - 0s - 4ms/step - loss: 13.1579 - val_loss: 21.6581
Epoch 81/100
29/29 - 0s - 4ms/step - loss: 13.2487 - val_loss: 18.1676
Epoch 82/100
29/29 - 0s - 6ms/step - loss: 12.7764 - val_loss: 20.2529
Epoch 83/100
29/29 - 0s - 4ms/step - loss: 12.6942 - val_loss: 16.5584
Epoch 84/100
29/29 - 0s - 4ms/step - loss: 14.1293 - val_loss: 17.4828
Epoch 85/100
29/29 - 0s - 4ms/step - loss: 16.2349 - val_loss: 25.7476
Epoch 86/100
29/29 - 0s - 4ms/step - loss: 15.0125 - val_loss: 16.6792
Epoch 87/100
29/29 - 0s - 4ms/step - loss: 12.8582 - val_loss: 16.9043
Epoch 88/100
29/29 - 0s - 7ms/step - loss: 11.9341 - val_loss: 25.0130
Epoch 89/100
29/29 - 0s - 7ms/step - loss: 12.2836 - val_loss: 19.5772
Epoch 90/100
29/29 - 0s - 6ms/step - loss: 12.2404 - val_loss: 18.9107
Epoch 91/100
29/29 - 0s - 4ms/step - loss: 13.4482 - val_loss: 20.3812
Epoch 92/100
29/29 - 0s - 4ms/step - loss: 12.7603 - val_loss: 19.9005
Epoch 93/100
29/29 - 0s - 4ms/step - loss: 12.3749 - val_loss: 20.4436
Epoch 94/100
29/29 - 0s - 4ms/step - loss: 12.4105 - val_loss: 16.8402
Epoch 95/100
29/29 - 0s - 4ms/step - loss: 11.9360 - val_loss: 17.9522
Epoch 96/100
29/29 - 0s - 4ms/step - loss: 12.0299 - val_loss: 19.4512
Epoch 97/100
29/29 - 0s - 4ms/step - loss: 13.3077 - val_loss: 16.2853
Epoch 98/100
29/29 - 0s - 4ms/step - loss: 12.8823 - val_loss: 16.9890
Epoch 99/100
29/29 - 0s - 4ms/step - loss: 11.3939 - val_loss: 20.6447
Epoch 100/100
29/29 - 0s - 4ms/step - loss: 12.0696 - val_loss: 32.3491

<!--
## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2024-11-20  | 3.0  | Aman  |  Updated the library versions to current |
| 2020-09-21  | 2.0  | Srishti  |  Migrated Lab to Markdown and added to course repo in GitLab |



<hr>

## <h3 align="center"> © IBM Corporation. All rights reserved. <h3/>